name: dataanalyzer
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- bamtools=2.5.1=he860b03_5
- bbmap=38.79=h516909a_0
- bedtools=2.29.2=hc088bd4_0
- bioconductor-biobase=2.42.0=r351h14c3975_1
- bioconductor-biocgenerics=0.28.0=r351_1
- bioconductor-biocparallel=1.16.6=r351h1c2f66e_0
- bioconductor-biostrings=2.50.2=r351h14c3975_0
- bioconductor-delayedarray=0.8.0=r351h14c3975_0
- bioconductor-genomeinfodb=1.18.1=r351_0
- bioconductor-genomeinfodbdata=1.2.1=r351_0
- bioconductor-genomicalignments=1.18.1=r351h14c3975_0
- bioconductor-genomicranges=1.34.0=r351h14c3975_0
- bioconductor-iranges=2.16.0=r351h14c3975_0
- bioconductor-noiseq=2.26.1=r351_0
- bioconductor-rsamtools=1.34.0=r351hf484d3e_0
- bioconductor-rtracklayer=1.42.1=r351h9d9f1b6_1
- bioconductor-s4vectors=0.20.1=r351h14c3975_0
- bioconductor-summarizedexperiment=1.12.0=r351_0
- bioconductor-xvector=0.22.0=r351h14c3975_0
- bioconductor-zlibbioc=1.28.0=r351h14c3975_0
- cutadapt=2.9=py37h516909a_0
- deeptools=3.4.2=py_0
- deeptoolsintervals=0.1.9=py37h516909a_0
- dnaio=0.4.1=py37h516909a_0
- fastqc=0.11.9=0
- htslib=1.10.2=h78d89cc_0
- meme=5.0.5=py37pl526h19b89cf_0
- multiqc=1.8=py_2
- perl-app-cpanminus=1.7044=pl526_1
- perl-base=2.23=pl526_1
- perl-carp=1.38=pl526_3
- perl-cgi=4.44=pl526h14c3975_1
- perl-common-sense=3.74=pl526_2
- perl-constant=1.33=pl526_1
- perl-dbi=1.642=pl526_0
- perl-encode=2.88=pl526_1
- perl-exporter=5.72=pl526_1
- perl-extutils-makemaker=7.36=pl526_1
- perl-file-path=2.16=pl526_0
- perl-file-temp=0.2304=pl526_2
- perl-file-which=1.23=pl526_0
- perl-html-parser=3.72=pl526h6bb024c_5
- perl-html-tagset=3.20=pl526_3
- perl-html-template=2.97=pl526_1
- perl-html-tree=5.07=pl526_1
- perl-json=4.02=pl526_0
- perl-json-xs=2.34=pl526h6bb024c_3
- perl-log-log4perl=1.49=pl526_0
- perl-math-cdf=0.1=pl526h14c3975_5
- perl-parent=0.236=pl526_1
- perl-scalar-list-utils=1.52=pl526h516909a_0
- perl-types-serialiser=1.0=pl526_2
- perl-xml-namespacesupport=1.12=pl526_0
- perl-xml-sax=1.02=pl526_0
- perl-xml-sax-base=1.09=pl526_0
- perl-xml-sax-expat=0.51=pl526_3
- perl-xml-simple=2.25=pl526_1
- perl-xsloader=0.24=pl526_0
- perl-yaml=1.29=pl526_0
- pureclip=1.3.1=0
- py2bit=0.3.0=py37h14c3975_2
- pybigwig=0.3.17=py37hc013797_0
- pysam=0.15.3=py37hbcae180_3
- qualimap=2.2.2d=1
- samtools=1.10=h9402c20_2
- star=2.7.3a=0
- subread=2.0.0=hed695b0_0
- ucsc-bedgraphtobigwig=357=h35c10e6_3
- umi_tools=1.0.1=py37h516909a_1
- _libgcc_mutex=0.1=conda_forge
- _openmp_mutex=4.5=0_gnu
- _r-mutex=1.0.1=anacondar_1
- alsa-lib=1.1.5=h516909a_1002
- binutils_impl_linux-64=2.34=h53a641e_0
- binutils_linux-64=2.34=hc952b39_18
- bwidget=1.9.14=0
- bzip2=1.0.8=h516909a_2
- ca-certificates=2020.4.5.1=hecc5488_0
- cairo=1.14.12=h80bd089_1005
- certifi=2020.4.5.1=py37hc8dfbb8_0
- cffi=1.14.0=py37hd463f26_0
- chardet=3.0.4=py37hc8dfbb8_1006
- click=7.1.1=pyh8c360ce_0
- cni=0.6.0=h8a17f66_1002
- cni-plugins=0.8.2=hc0beb16_0
- coloredlogs=14.0=py37hc8dfbb8_1
- colormath=3.0.0=py_2
- cryptography=2.8=py37hb09aad4_2
- curl=7.68.0=hf8cf82a_0
- cycler=0.10.0=py_2
- decorator=4.4.2=py_0
- expat=2.2.9=he1b5a44_2
- font-ttf-dejavu-sans-mono=2.37=hab24e00_0
- font-ttf-inconsolata=2.001=hab24e00_0
- font-ttf-source-code-pro=2.030=hab24e00_0
- font-ttf-ubuntu=0.83=hab24e00_0
- fontconfig=2.13.1=he4413a7_1000
- fonts-conda-ecosystem=1=0
- fonts-conda-forge=1=0
- freetype=2.10.1=he06d7ca_0
- future=0.18.2=py37hc8dfbb8_1
- gcc_impl_linux-64=7.3.0=hd420e75_5
- gcc_linux-64=7.3.0=h553295d_18
- gettext=0.19.8.1=hc5be6a0_1002
- gfortran_impl_linux-64=7.3.0=hdf63c60_5
- gfortran_linux-64=7.3.0=h553295d_18
- ghostscript=9.22=hf484d3e_1001
- giflib=5.2.1=h516909a_2
- glib=2.56.2=had28632_1001
- graphite2=1.3.13=he1b5a44_1001
- gxx_impl_linux-64=7.3.0=hdf63c60_5
- gxx_linux-64=7.3.0=h553295d_18
- harfbuzz=1.9.0=he243708_1001
- humanfriendly=8.1=py37hc8dfbb8_1
- icu=58.2=hf484d3e_1000
- idna=2.9=py_1
- jinja2=2.11.2=pyh9f0ad1d_0
- jpeg=9c=h14c3975_1001
- jq=1.6=h14c3975_1000
- kiwisolver=1.2.0=py37h99015e2_0
- krb5=1.16.4=h2fd8d38_0
- lcms2=2.9=hbd6801e_1
- ld_impl_linux-64=2.34=h53a641e_0
- libblas=3.8.0=14_openblas
- libcblas=3.8.0=14_openblas
- libcurl=7.68.0=hda55be3_0
- libdeflate=1.3=h516909a_0
- libedit=3.1.20170329=hf8c457e_1001
- libffi=3.2.1=he1b5a44_1007
- libgcc-ng=9.2.0=h24d8f2e_2
- libgfortran-ng=7.3.0=hdf63c60_5
- libgomp=9.2.0=h24d8f2e_2
- libiconv=1.15=h516909a_1006
- liblapack=3.8.0=14_openblas
- libopenblas=0.3.7=h5ec1e0e_6
- libpng=1.6.37=hed695b0_1
- libseccomp=2.4.1=h516909a_0
- libssh2=1.8.2=h22169c7_2
- libstdcxx-ng=9.2.0=hdf63c60_2
- libuuid=2.32.1=h14c3975_1000
- libwebp-base=1.1.0=h516909a_3
- libxcb=1.13=h14c3975_1002
- libxml2=2.9.9=h13577e0_2
- libxslt=1.1.32=hae48121_1003
- lz4=3.0.2=py37hb076c26_1
- lz4-c=1.8.3=he1b5a44_1001
- lzo=2.10=h14c3975_1000
- lzstring=1.0.4=py_1001
- make=4.3=h516909a_0
- markdown=3.2.1=py_0
- markupsafe=1.1.1=py37h8f50634_1
- matplotlib-base=3.1.1=py37hfd891ef_0
- mpi=1.0=openmpi
- ncurses=6.1=hf484d3e_1002
- networkx=2.2=py_1
- numpy=1.18.1=py37h8960a57_1
- oniguruma=6.9.3=h516909a_0
- openjdk=11.0.1=h600c080_1018
- openmpi=4.0.3=hdf1f1ad_1
- openssl=1.1.1f=h516909a_0
- pandas=1.0.3=py37h0da4684_0
- pango=1.40.14=hf0c64fd_1003
- pcre=8.44=he1b5a44_0
- perl=5.26.2=h516909a_1006
- perl-xml-parser=2.44_01=pl526ha1d75be_1002
- pigz=2.3.4=hed695b0_1
- pip=20.0.2=py_2
- pixman=0.34.0=h14c3975_1003
- plotly=4.6.0=pyh9f0ad1d_0
- pthread-stubs=0.4=h14c3975_1001
- pycparser=2.20=py_0
- pyopenssl=19.1.0=py_1
- pyparsing=2.4.7=pyh9f0ad1d_0
- pysocks=1.7.1=py37hc8dfbb8_1
- python=3.7.3=h5b0a415_0
- python-dateutil=2.8.1=py_0
- python_abi=3.7=1_cp37m
- pytz=2019.3=py_0
- pyyaml=5.1.2=py37h516909a_0
- r-base=3.5.1=he45234b_1005
- r-bh=1.72.0_3=r35h6115d3f_0
- r-bitops=1.0_6=r35hcdcec82_1003
- r-formatr=1.7=r35h6115d3f_1
- r-futile.logger=1.4.3=r35h6115d3f_1002
- r-futile.options=1.0.1=r35h6115d3f_1001
- r-getopt=1.20.3=r35_1
- r-lambda.r=1.2.4=r35h6115d3f_0
- r-lattice=0.20_41=r35hcdcec82_0
- r-matrix=1.2_18=r35hcdcec82_0
- r-matrixstats=0.56.0=r35hcdcec82_0
- r-optparse=1.6.4=r35h6115d3f_0
- r-rcurl=1.98_1.1=r35hcdcec82_0
- r-snow=0.4_3=r35h6115d3f_1001
- r-xml=3.98_1.20=r35hcdcec82_1
- readline=7.0=hf8c457e_1001
- regex=2020.4.4=py37h8f50634_0
- requests=2.23.0=pyh8c360ce_2
- retrying=1.3.3=py_2
- scipy=1.4.1=py37ha3d9a3c_3
- setuptools=46.1.3=py37hc8dfbb8_0
- simplejson=3.17.0=py37h516909a_0
- singularity=3.5.3=h6227a62_0
- six=1.14.0=py_1
- spectra=0.0.11=py_1
- sqlite=3.28.0=h8b20d00_0
- squashfs-tools=4.3=h54f8c30_1003
- tk=8.6.10=hed695b0_0
- tktable=2.10=h555a92e_3
- tornado=6.0.4=py37h8f50634_1
- urllib3=1.25.8=py37hc8dfbb8_1
- wheel=0.34.2=py_1
- xopen=0.9.0=py37hc8dfbb8_0
- xorg-fixesproto=5.0=h14c3975_1002
- xorg-inputproto=2.3.2=h14c3975_1002
- xorg-kbproto=1.0.7=h14c3975_1002
- xorg-libice=1.0.10=h516909a_0
- xorg-libsm=1.2.3=h84519dc_1000
- xorg-libx11=1.6.9=h516909a_0
- xorg-libxau=1.0.9=h14c3975_0
- xorg-libxdmcp=1.1.3=h516909a_0
- xorg-libxext=1.3.4=h516909a_0
- xorg-libxfixes=5.0.3=h516909a_1004
- xorg-libxi=1.7.10=h516909a_0
- xorg-libxrender=0.9.10=h516909a_1002
- xorg-libxtst=1.2.3=h516909a_1002
- xorg-recordproto=1.14.2=h516909a_1002
- xorg-renderproto=0.11.1=h14c3975_1002
- xorg-xextproto=7.3.0=h14c3975_1002
- xorg-xproto=7.0.31=h14c3975_1007
- xz=5.2.5=h516909a_0
- yaml=0.1.7=h14c3975_1001
- zlib=1.2.11=h516909a_1006
- zstd=1.3.7=h0a35d5f_1001
- libarchive=3.3.3=h5d8350f_5
- libtiff=4.1.0=h2733197_0
- mysql-connector-c=6.1.11=h597af5e_1
prefix: /N/u/jbuddika/Carbonate/.conda/envs/dataanalyzer

